export { GeneralTab } from './GeneralTab'
export { PlatformsTab } from './PlatformsTab'
export { InteractionTab } from './InteractionTab'
export { AliasesTab } from './AliasesTab'
export { NotifyTab } from './NotifyTab'
export type { TabProps } from './types'
